name: islamic_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.0.0
  gradient_borders: ^1.0.1
  http: ^1.3.0
  intl: ^0.20.2
  path: ^1.9.1
  provider: ^6.1.2
  quran_library: ^0.1.3
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "icon.png" 


flutter:
  uses-material-design: true
  
